#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ load("lib.star", "documents")
#@ load("server.lib.yml", "server", "singleton")

#@ template.replace(documents(data, server, None, singleton))
